enableGlobalCache: true

packageExtensions:
  gulp-javascript-obfuscator@*:
    dependencies:
      vinyl-sourcemaps-apply: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
